services:
  db:
    image: postgres:16
    container_name: postgres-db2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: elbahia2005
      POSTGRES_DB: RetentionAI
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: C:/Users/hp/OneDrive/Documents/retentionAI
      dockerfile: Docker/Dockerfile
    container_name: fastapi-backend2
    ports:
      - "8000:8000"
    volumes:
      - C:/Users/hp/OneDrive/Documents/retentionAI:/app
    env_file:
      - C:/Users/hp/OneDrive/Documents/retentionAI/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: C:/Users/hp/OneDrive/Documents/retentionAI_front
      dockerfile: Dockerfile
    container_name: nextjs-frontend2
    ports:
      - "3001:3000"
    volumes:
      - C:/Users/hp/OneDrive/Documents/retentionAI_front:/app
      - /app/node_modules
      - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
